# Generated by Django 4.2.30 on 2026-07-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0024_alter_deployment_goarch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnmpDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('printer', 'Printer'), ('ups', 'UPS'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('nas', 'NAS'), ('other', 'Other')], default='printer', max_length=20)),
                ('ip', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=161)),
                ('community', models.CharField(default='public', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('offline_minutes', models.PositiveIntegerField(default=30)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_devices', to='clients.site')),
            ],
            options={
                'ordering': ('site', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SnmpReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='qdt_snmp.snmpdevice')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['device', 'metric', '-timestamp'], name='qdt_snmp_sn_device__204ff1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='snmpdevice',
            constraint=models.UniqueConstraint(fields=('site', 'ip', 'port'), name='unique_snmp_device_per_site'),
        ),
    ]
