# Generated by Django 4.2.30 on 2026-07-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdt_snmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpdevice',
            name='metric_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
