# Generated by Django 4.2.30 on 2026-07-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alerttemplate_action_rest_alerttemplate_action_type_and_more'),
        ('qdt_snmp', '0002_snmpdevice_metric_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpdevice',
            name='email_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snmpdevice',
            name='thresholds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SnmpAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='qdt_snmp.snmpdevice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='snmpalert',
            constraint=models.UniqueConstraint(fields=('device', 'metric'), name='unique_open_snmp_alert_per_metric'),
        ),
    ]
